spring.datasource.url=jdbc:postgresql://ep-muddy-bonus-anudokrd-pooler.c-6.us-east-1.aws.neon.tech:5432/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_RSTjXU5y0bwi

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true